### ISSUE TITLE
Excel and data are having new information

### ISSUE THREAD

**Issue by ghost** [NicolasWoloszko/OECD-Weekly-Tracker#1]
Hi Nicolas, 

I don't know if it its on porpurse but your graphs and data are getting new information on "counterfactual" that you didnt used to have. Can you please explain or specify on the page what is the counterfactual information about? 

Thanks, 
Diego

**Comment by NicolasWoloszko** [comment]
Hi Diego, 
Yes, please refer to the explanations given on the Tracker website: 
https://www.oecd.org/economy/weekly-tracker-of-gdp-growth/
Best, 
Nicolas
