### ISSUE TITLE
quarter_on_quarter_Q1_2021.xlsx doesnt match weekly_tracker.xlsx yoy estimate

### ISSUE THREAD

**Issue by ghost** [NicolasWoloszko/OECD-Weekly-Tracker#2]
Hi Nicolas, 

I am trying to replicate quarter on quarter growth in the first xlsx that I mention. But the numbers that I am using don´t match the final results. 

When I use the weekly tracker information YoY average growth of the weeks corresponding to Q1 of 2021 and Q4 of 2020 times Q1 2020 of the Quarter on Quarter growth from the OECD database it gives me a big difference with the actual forecast for the current quarter.  Maybe I am doing something wrong. 

Specific Example USA: 

Currently, the YoY growth of the tracker is 3,3% for Q1 2021 and -2,2% for Q42020, using the -1,3% QoQ growth of the OECD national account for Q1 2020, I get that the actual QoQ growth for Q1 should be close to 4,3%. But in the meantime the current Quarter on Quarter forecast with the model is close to 1,7%. 

I've tried using  the Yo2Y Q1 2021 and Q4 2020, but still kind of far of the actual number of quarter_quarter_Q1_2021.xlsx 

Can you help me with this?
Best regards,
Diego

**Comment by NicolasWoloszko** [comment]
That's because qoq is quarter on quarter whereas yoy is 1-year growth rate. See Deriving quarter-on-quarter quarterly estimates in https://www.oecd.org/economy/weekly-tracker-of-gdp-growth/
